# Generated by Django 3.2.3 on 2021-05-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('opening_price', models.FloatField()),
                ('closing_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('units_traded', models.FloatField()),
                ('acc_trade_value', models.FloatField()),
                ('prev_closing_price', models.FloatField()),
                ('units_traded_24H', models.FloatField()),
                ('acc_trade_value_24H', models.FloatField()),
                ('fluctate_24H', models.FloatField()),
                ('fluctate_rate_24H', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
