# Generated by Django 3.2.3 on 2021-05-20 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('account', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.coin'),
        ),
    ]
