# Generated by Django 3.2.3 on 2021-05-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_transaction_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price_amount',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
