# Generated by Django 3.2.3 on 2021-05-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210520_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='buy', max_length=10),
        ),
    ]
