# Generated by Django 3.2.3 on 2021-05-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveBigIntegerField(default=100000000),
        ),
    ]
